apiVersion: apps/v1
kind: Deployment
metadata:
  name: ffmpeg
  namespace: monitoring
  labels:
    app: ffmpeg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ffmpeg
  template:
    metadata:
      labels:
        app: ffmpeg
    spec:
      containers:
      - name: ffmpeg
        image: katiadesimone/progetto:v1.1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ffmpeg
  namespace: monitoring
spec:
  ports:
    - port: 80
      targetPort: 30080
      nodePort: 30080
      protocol: TCP
  selector:
    app: ffmpeg
  sessionAffinity: None
  type: LoadBalancer
